/* User */
ALTER TABLE [dbo].[USER] ADD  CONSTRAINT [FK_User_UserDefinable] FOREIGN KEY([Id]) REFERENCES [dbo].[USER_DEFINABLE] ([Id])
GO

/* Exhibition */
ALTER TABLE [dbo].[EXHIBITION] ADD  CONSTRAINT [FK_Exhibition_UserDefinable] FOREIGN KEY([Id]) REFERENCES [dbo].[USER_DEFINABLE] ([Id])
GO

/* Painting */
ALTER TABLE [dbo].[PAINTING] ADD  CONSTRAINT [FK_Painting_UserDefinable] FOREIGN KEY([Id]) REFERENCES [dbo].[USER_DEFINABLE] ([Id])
GO
ALTER TABLE [dbo].[PAINTING] ADD  CONSTRAINT [FK_Painting_Collection] FOREIGN KEY([CollectionId]) REFERENCES [dbo].[COLLECTION] ([Id]) ON DELETE SET NULL
GO

/* Collection */
ALTER TABLE [dbo].[COLLECTION] ADD  CONSTRAINT [FK_Collection_UserDefinable] FOREIGN KEY([Id]) REFERENCES [dbo].[USER_DEFINABLE] ([Id])
GO

/* UserDefinable */
ALTER TABLE [dbo].[USER_DEFINABLE] ADD CONSTRAINT [FK_UserDefinable_User] FOREIGN KEY ([UserCreatorId]) REFERENCES [dbo].[USER] (Id)
GO

/* Join_Painting_Exhibition */
ALTER TABLE [dbo].[JOIN_PAINTING_EXHIBITION] ADD CONSTRAINT [FK_Join_PaintingExhibition_Painting] FOREIGN KEY ([PaintingId]) REFERENCES [dbo].[PAINTING] (Id) ON DELETE CASCADE
GO
ALTER TABLE [dbo].[JOIN_PAINTING_EXHIBITION] ADD CONSTRAINT [FK_Join_PaintingExhibition_Exhibition] FOREIGN KEY ([ExhibitionId]) REFERENCES [dbo].[EXHIBITION] (Id) ON DELETE CASCADE
GO

/* Join_User_Painting */
ALTER TABLE [dbo].[JOIN_USER_PAINTING] ADD CONSTRAINT [FK_Join_UserPainting_User] FOREIGN KEY ([UserId]) REFERENCES [dbo].[USER] (Id) ON DELETE CASCADE
GO
ALTER TABLE [dbo].[JOIN_USER_PAINTING] ADD CONSTRAINT [FK_Join_UserPainting_Painting] FOREIGN KEY ([PaintingId]) REFERENCES [dbo].[PAINTING] (Id) ON DELETE CASCADE
GO

/* Menu Item */
ALTER TABLE [dbo].[MENU_ITEM] ADD CONSTRAINT [FK_MenuItem_ParentMenuItem] FOREIGN KEY ([ParentMenuItemId]) REFERENCES [dbo].[MENU_ITEM] (Id)
GO
ALTER TABLE [dbo].[MENU_ITEM] ADD CONSTRAINT [FK_MenuItem_UserDefinable] FOREIGN KEY ([UserDefinableId]) REFERENCES [dbo].[USER_DEFINABLE] (Id)
GO

/* Resources */
ALTER TABLE [dbo].[RESOURCE] ADD CONSTRAINT [FK_RESOURCE_USER_DEFINABLE] FOREIGN KEY ([UserDefinableId]) REFERENCES [dbo].[USER_DEFINABLE](Id)
GO

/* Gallery */
ALTER TABLE [dbo].[GALLERY] ADD CONSTRAINT [FK_GALLERY_OWNER] FOREIGN KEY ([OwnerId]) REFERENCES [dbo].[USER_DEFINABLE] (Id)
GO
ALTER TABLE [dbo].[GALLERY] ADD CONSTRAINT [FK_GALLERY_COVER_PHOTO] FOREIGN KEY ([CoverPhotoId]) REFERENCES [dbo].[RESOURCE] (Id)
GO