ALTER TABLE [dbo].[USER] ADD CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED ([Id] ASC)
GO
ALTER TABLE [dbo].[ROLE] ADD CONSTRAINT [PK_Role] PRIMARY KEY CLUSTERED ([Id] ASC)
GO
ALTER TABLE [dbo].[MENU_ITEM] ADD CONSTRAINT [PK_MenuItem] PRIMARY KEY CLUSTERED ([Id] ASC)
GO
ALTER TABLE [dbo].[RESOURCE] ADD CONSTRAINT [PK_Resource] PRIMARY KEY CLUSTERED ([Id] ASC)
GO
ALTER TABLE [dbo].[USER_DEFINABLE] ADD CONSTRAINT [PK_UserDefinable] PRIMARY KEY CLUSTERED ([Id] ASC)
GO