CREATE TABLE [dbo].[EXHIBITION]
(
	[Id] UNIQUEIDENTIFIER NOT NULL,
	[Name] NVARCHAR(MAX) NOT NULL,
	[Address] NVARCHAR(MAX) NULL,
	[City] NVARCHAR(MAX) NULL,
	[Zipcode] NVARCHAR(MAX) NULL,
	[Gps] NVARCHAR(MAX) NULL,
	[Start] DATETIME NOT NULL,
	[End] DATETIME NOT NULL,
	[Description] NVARCHAR(MAX) NULL
)
