CREATE TABLE [dbo].[GALLERY]
(
	[Id] UNIQUEIDENTIFIER NOT NULL,
	[Name] NVARCHAR(MAX) NOT NULL,
	[CoverPhotoId] UNIQUEIDENTIFIER NULL,
	[OwnerId] UNIQUEIDENTIFIER NOT NULL,
	[Discriminator] NVARCHAR(128) NOT NULL,
)
