CREATE TABLE [dbo].[USER]
(
	[Id] UNIQUEIDENTIFIER NOT NULL,
	[FirstName] NVARCHAR(MAX) NOT NULL,
	[Surname] NVARCHAR(MAX) NOT NULL,
	[Email] NVARCHAR(MAX) NOT NULL,
	[Password] NVARCHAR(MAX) NOT NULL,
	[Description] NVARCHAR(MAX) NULL,

	[RoleId] UNIQUEIDENTIFIER NOT NULL,
)

