//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared.I18n.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shared.I18n.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skutečně chcete vymazat daný objekt?.
        /// </summary>
        public static string delete_information_message {
            get {
                return ResourceManager.GetString("delete_information_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akryl.
        /// </summary>
        public static string label_acrylic {
            get {
                return ResourceManager.GetString("label_acrylic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přidat umělce.
        /// </summary>
        public static string label_add_artist {
            get {
                return ResourceManager.GetString("label_add_artist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přidat kolekci.
        /// </summary>
        public static string label_add_collection {
            get {
                return ResourceManager.GetString("label_add_collection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přidat výstavu.
        /// </summary>
        public static string label_add_exhibition {
            get {
                return ResourceManager.GetString("label_add_exhibition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přidat obraz.
        /// </summary>
        public static string label_add_painting {
            get {
                return ResourceManager.GetString("label_add_painting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přidat roli.
        /// </summary>
        public static string label_add_role {
            get {
                return ResourceManager.GetString("label_add_role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresa.
        /// </summary>
        public static string label_address {
            get {
                return ResourceManager.GetString("label_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akvarel.
        /// </summary>
        public static string label_aquarel {
            get {
                return ResourceManager.GetString("label_aquarel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Umělci.
        /// </summary>
        public static string label_artists {
            get {
                return ResourceManager.GetString("label_artists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autor.
        /// </summary>
        public static string label_author {
            get {
                return ResourceManager.GetString("label_author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plátno.
        /// </summary>
        public static string label_canvas {
            get {
                return ResourceManager.GetString("label_canvas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Křída.
        /// </summary>
        public static string label_chalk {
            get {
                return ResourceManager.GetString("label_chalk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Změnit obrazy.
        /// </summary>
        public static string label_change_paintings {
            get {
                return ResourceManager.GetString("label_change_paintings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Změnit heslo.
        /// </summary>
        public static string label_change_password {
            get {
                return ResourceManager.GetString("label_change_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Město.
        /// </summary>
        public static string label_city {
            get {
                return ResourceManager.GetString("label_city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zavřít.
        /// </summary>
        public static string label_close {
            get {
                return ResourceManager.GetString("label_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kolekce.
        /// </summary>
        public static string label_collection {
            get {
                return ResourceManager.GetString("label_collection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kolekce.
        /// </summary>
        public static string label_collections {
            get {
                return ResourceManager.GetString("label_collections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrzení.
        /// </summary>
        public static string label_confirmation {
            get {
                return ResourceManager.GetString("label_confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokračovat.
        /// </summary>
        public static string label_continue {
            get {
                return ResourceManager.GetString("label_continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pastelky.
        /// </summary>
        public static string label_crayons {
            get {
                return ResourceManager.GetString("label_crayons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrace dat.
        /// </summary>
        public static string label_create_update_delete_all {
            get {
                return ResourceManager.GetString("label_create_update_delete_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dokončeno.
        /// </summary>
        public static string label_date_finish {
            get {
                return ResourceManager.GetString("label_date_finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vymazat všechny obrazy v kolekci.
        /// </summary>
        public static string label_delete_all_paintings {
            get {
                return ResourceManager.GetString("label_delete_all_paintings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popis.
        /// </summary>
        public static string label_description {
            get {
                return ResourceManager.GetString("label_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přesunout fotografie sem.
        /// </summary>
        public static string label_drop_photos {
            get {
                return ResourceManager.GetString("label_drop_photos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string label_email {
            get {
                return ResourceManager.GetString("label_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konec.
        /// </summary>
        public static string label_end {
            get {
                return ResourceManager.GetString("label_end", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadejte e-mailovou adresu.
        /// </summary>
        public static string label_enter_email {
            get {
                return ResourceManager.GetString("label_enter_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadejte heslo.
        /// </summary>
        public static string label_enter_password {
            get {
                return ResourceManager.GetString("label_enter_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Výstavy.
        /// </summary>
        public static string label_exhibitions {
            get {
                return ResourceManager.GetString("label_exhibitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyplnit formulář.
        /// </summary>
        public static string label_fill_form {
            get {
                return ResourceManager.GetString("label_fill_form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jméno.
        /// </summary>
        public static string label_firstname {
            get {
                return ResourceManager.GetString("label_firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapomněli jste heslo?.
        /// </summary>
        public static string label_forgot_password {
            get {
                return ResourceManager.GetString("label_forgot_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generuj průvodce.
        /// </summary>
        public static string label_generate_guide {
            get {
                return ResourceManager.GetString("label_generate_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sklo.
        /// </summary>
        public static string label_glass {
            get {
                return ResourceManager.GetString("label_glass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPS pozice.
        /// </summary>
        public static string label_gps {
            get {
                return ResourceManager.GetString("label_gps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Výška.
        /// </summary>
        public static string label_height {
            get {
                return ResourceManager.GetString("label_height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domů.
        /// </summary>
        public static string label_home {
            get {
                return ResourceManager.GetString("label_home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seznam.
        /// </summary>
        public static string label_list {
            get {
                return ResourceManager.GetString("label_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odhlásit.
        /// </summary>
        public static string label_logout {
            get {
                return ResourceManager.GetString("label_logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string label_menu {
            get {
                return ResourceManager.GetString("label_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrace menu.
        /// </summary>
        public static string label_menu_creation {
            get {
                return ResourceManager.GetString("label_menu_creation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jméno.
        /// </summary>
        public static string label_name {
            get {
                return ResourceManager.GetString("label_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nové heslo.
        /// </summary>
        public static string label_new_password {
            get {
                return ResourceManager.GetString("label_new_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nové heslo (znovu).
        /// </summary>
        public static string label_new_password_again {
            get {
                return ResourceManager.GetString("label_new_password_again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ne.
        /// </summary>
        public static string label_no {
            get {
                return ResourceManager.GetString("label_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olej.
        /// </summary>
        public static string label_oil {
            get {
                return ResourceManager.GetString("label_oil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Původní heslo.
        /// </summary>
        public static string label_old_password {
            get {
                return ResourceManager.GetString("label_old_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Majitel.
        /// </summary>
        public static string label_owner {
            get {
                return ResourceManager.GetString("label_owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malby.
        /// </summary>
        public static string label_paintings {
            get {
                return ResourceManager.GetString("label_paintings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Počet obrazů.
        /// </summary>
        public static string label_paintings_count {
            get {
                return ResourceManager.GetString("label_paintings_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Papír.
        /// </summary>
        public static string label_paper {
            get {
                return ResourceManager.GetString("label_paper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heslo.
        /// </summary>
        public static string label_password {
            get {
                return ResourceManager.GetString("label_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pastel.
        /// </summary>
        public static string label_pastel {
            get {
                return ResourceManager.GetString("label_pastel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pero.
        /// </summary>
        public static string label_pen {
            get {
                return ResourceManager.GetString("label_pen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tužka.
        /// </summary>
        public static string label_pencil {
            get {
                return ResourceManager.GetString("label_pencil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosím, přihlašte se.
        /// </summary>
        public static string label_please_sign_in {
            get {
                return ResourceManager.GetString("label_please_sign_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zpět.
        /// </summary>
        public static string label_previous {
            get {
                return ResourceManager.GetString("label_previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil.
        /// </summary>
        public static string label_profile {
            get {
                return ResourceManager.GetString("label_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string label_role {
            get {
                return ResourceManager.GetString("label_role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrace rolí.
        /// </summary>
        public static string label_role_creation {
            get {
                return ResourceManager.GetString("label_role_creation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string label_roles {
            get {
                return ResourceManager.GetString("label_roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uložit.
        /// </summary>
        public static string label_save {
            get {
                return ResourceManager.GetString("label_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Všechny obrazy v kolekci zachovat.
        /// </summary>
        public static string label_set_paintings_to_default_collection {
            get {
                return ResourceManager.GetString("label_set_paintings_to_default_collection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přihlásit se.
        /// </summary>
        public static string label_sign_in {
            get {
                return ResourceManager.GetString("label_sign_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozměry.
        /// </summary>
        public static string label_size {
            get {
                return ResourceManager.GetString("label_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sololit.
        /// </summary>
        public static string label_sololit {
            get {
                return ResourceManager.GetString("label_sololit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Začátek.
        /// </summary>
        public static string label_start {
            get {
                return ResourceManager.GetString("label_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Povrch.
        /// </summary>
        public static string label_surface {
            get {
                return ResourceManager.GetString("label_surface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Příjmení.
        /// </summary>
        public static string label_surname {
            get {
                return ResourceManager.GetString("label_surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technika.
        /// </summary>
        public static string label_technique {
            get {
                return ResourceManager.GetString("label_technique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tempera.
        /// </summary>
        public static string label_temper {
            get {
                return ResourceManager.GetString("label_temper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Čas.
        /// </summary>
        public static string label_time {
            get {
                return ResourceManager.GetString("label_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Název.
        /// </summary>
        public static string label_title {
            get {
                return ResourceManager.GetString("label_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nahrát fotky.
        /// </summary>
        public static string label_upload_photos {
            get {
                return ResourceManager.GetString("label_upload_photos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrace uživatelů.
        /// </summary>
        public static string label_user_creation {
            get {
                return ResourceManager.GetString("label_user_creation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Více informací.
        /// </summary>
        public static string label_view_details {
            get {
                return ResourceManager.GetString("label_view_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šířka.
        /// </summary>
        public static string label_width {
            get {
                return ResourceManager.GetString("label_width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dřevo.
        /// </summary>
        public static string label_wood {
            get {
                return ResourceManager.GetString("label_wood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ano.
        /// </summary>
        public static string label_yes {
            get {
                return ResourceManager.GetString("label_yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSČ.
        /// </summary>
        public static string label_zipcode {
            get {
                return ResourceManager.GetString("label_zipcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; je neplatný e-mail.
        /// </summary>
        public static string validation_email_message {
            get {
                return ResourceManager.GetString("validation_email_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soubor je ve špatném formátu. Očekáván je typ &apos;{0}&apos;.
        /// </summary>
        public static string validation_file_is_in_wrong_format_message {
            get {
                return ResourceManager.GetString("validation_file_is_in_wrong_format_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soubor &apos;{0}&apos; je příliš velký. Maximální velikost může být &apos;{1}&apos; MB.
        /// </summary>
        public static string validation_file_is_oversized_message {
            get {
                return ResourceManager.GetString("validation_file_is_oversized_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozměry obrázku jsou &apos;{0} x {1}&apos;. Minimálně však musí být &apos;{2} x {3}&apos;.
        /// </summary>
        public static string validation_image_minimum_size_message {
            get {
                return ResourceManager.GetString("validation_image_minimum_size_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Počet fotografií pro daný objekt nesmí přesáhnout limit &apos;{0}&apos;.
        /// </summary>
        public static string validation_maximum_resources_reached_message {
            get {
                return ResourceManager.GetString("validation_maximum_resources_reached_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nová hesla nejsou stejná.
        /// </summary>
        public static string validation_new_passwords_not_equal_message {
            get {
                return ResourceManager.GetString("validation_new_passwords_not_equal_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objekt se používá.
        /// </summary>
        public static string validation_object_is_used_message {
            get {
                return ResourceManager.GetString("validation_object_is_used_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objekt s hodnotou &apos;{0}&apos; už existuje.
        /// </summary>
        public static string validation_object_with_value_already_exists_message {
            get {
                return ResourceManager.GetString("validation_object_with_value_already_exists_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Původní heslo je chybné.
        /// </summary>
        public static string validation_old_password_wrong_message {
            get {
                return ResourceManager.GetString("validation_old_password_wrong_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chyba při zpracování multi-vkládání dat.
        /// </summary>
        public static string validation_parse_bulk_input_message {
            get {
                return ResourceManager.GetString("validation_parse_bulk_input_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hodnota &apos;{0}&apos; musí být mezi &apos;{1}&apos; a &apos;{2}&apos;.
        /// </summary>
        public static string validation_range_message {
            get {
                return ResourceManager.GetString("validation_range_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hodnota &apos;{0}&apos; je povinná.
        /// </summary>
        public static string validation_required_message {
            get {
                return ResourceManager.GetString("validation_required_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; je neplatná url adresa.
        /// </summary>
        public static string validation_url_message {
            get {
                return ResourceManager.GetString("validation_url_message", resourceCulture);
            }
        }
    }
}
