//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared.I18n.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shared.I18n.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zavřít.
        /// </summary>
        public static string label_close {
            get {
                return ResourceManager.GetString("label_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrzení.
        /// </summary>
        public static string label_confirmation {
            get {
                return ResourceManager.GetString("label_confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokračovat.
        /// </summary>
        public static string label_continue {
            get {
                return ResourceManager.GetString("label_continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popis.
        /// </summary>
        public static string label_description {
            get {
                return ResourceManager.GetString("label_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přesunout fotografie sem.
        /// </summary>
        public static string label_drop_photos {
            get {
                return ResourceManager.GetString("label_drop_photos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string label_email {
            get {
                return ResourceManager.GetString("label_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyplnit formulář.
        /// </summary>
        public static string label_fill_form {
            get {
                return ResourceManager.GetString("label_fill_form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jméno.
        /// </summary>
        public static string label_firstname {
            get {
                return ResourceManager.GetString("label_firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domů.
        /// </summary>
        public static string label_home {
            get {
                return ResourceManager.GetString("label_home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string label_menu {
            get {
                return ResourceManager.GetString("label_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrace menu.
        /// </summary>
        public static string label_menu_creation {
            get {
                return ResourceManager.GetString("label_menu_creation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ne.
        /// </summary>
        public static string label_no {
            get {
                return ResourceManager.GetString("label_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string label_role {
            get {
                return ResourceManager.GetString("label_role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrace rolí.
        /// </summary>
        public static string label_role_creation {
            get {
                return ResourceManager.GetString("label_role_creation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string label_roles {
            get {
                return ResourceManager.GetString("label_roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uložit.
        /// </summary>
        public static string label_save {
            get {
                return ResourceManager.GetString("label_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Příjmení.
        /// </summary>
        public static string label_surname {
            get {
                return ResourceManager.GetString("label_surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ano.
        /// </summary>
        public static string label_yes {
            get {
                return ResourceManager.GetString("label_yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; je neplatný e-mail.
        /// </summary>
        public static string validation_email_message {
            get {
                return ResourceManager.GetString("validation_email_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hodnota &apos;{0}&apos; musí být mezi &apos;{1}&apos; a &apos;{2}&apos;.
        /// </summary>
        public static string validation_range_message {
            get {
                return ResourceManager.GetString("validation_range_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hodnota &apos;{0}&apos; je povinná.
        /// </summary>
        public static string validation_required_message {
            get {
                return ResourceManager.GetString("validation_required_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; je neplatná url adresa.
        /// </summary>
        public static string validation_url_message {
            get {
                return ResourceManager.GetString("validation_url_message", resourceCulture);
            }
        }
    }
}
